<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="71849" started-at="2021-07-19T16:28:32Z" finished-at="2021-07-19T16:29:44Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="71849" started-at="2021-07-19T16:28:32Z" finished-at="2021-07-19T16:29:44Z">
      <class name="assignment.Tests">
        <test-method status="PASS" signature="accuWheatherAPI()[pri:0, instance:assignment.Tests@6a4f787b]" name="accuWheatherAPI" duration-ms="2934" started-at="2021-07-19T21:58:32Z" finished-at="2021-07-19T21:58:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- accuWheatherAPI -->
        <test-method status="PASS" signature="loginToWheather()[pri:1, instance:assignment.Tests@6a4f787b]" name="loginToWheather" duration-ms="68889" started-at="2021-07-19T21:58:35Z" finished-at="2021-07-19T21:59:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToWheather -->
        <test-method status="FAIL" signature="validateTemp()[pri:3, instance:assignment.Tests@6a4f787b]" name="validateTemp" duration-ms="4" started-at="2021-07-19T21:59:44Z" finished-at="2021-07-19T21:59:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed due to temp difference expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed due to temp difference expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at assignment.Tests.validateTemp(Tests.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTemp -->
      </class> <!-- assignment.Tests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
